version: '3'

services:
  server:
    container_name: NODEJS_SERVER_MEDIUM
    restart: always
    env_file:
        - .env
    build: '.'
    volumes:
      - ./:/node-app
      - ./node_modules:/node-app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - db
    links:
      - db
    ports:
      - '${PORT}:${PORT}'

    
      

  db:
    image: 'mongo'
    env_file:
      - .env
    container_name: MONGODB_MEDIUM
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - '${DB_PORT}:27017'
    volumes:
      - ./data/db:/data/dbdocke
   